### ISSUE TITLE
Can't run plugin

### ISSUE THREAD

**Issue by ziflex** [dehuszar/postcss-reference#1] opened 2016-02-15 14:54 UTC
Hi there,

today I decided to try this plugin and unfortunately was not able to make it work.

Here is my simple button.css file:

```css
    @reference {
        @import "../../../node_modules/bootstrap/dist/css/bootstrap.css";
     }

    .button {
        @references .btn, .btn-default;
    }
```

and my gulp task:

```js

    return $.gulp.src(env.paths.input + '/**/*.css')
        .pipe($.postcss([
            require('postcss-import'),
            require('postcss-nested'),
            require('postcss-reference'),
            require('css-mqpacker')
        ]))
        .pipe($.gulp.dest(env.paths.output))

```

output:

```css

    .button {
    }

```

**Comment by ai** [comment] 2016-02-15 14:56
@ziflex what is your CSS output?

**Comment by ziflex** [comment] 2016-02-15 15:00
@ai updated

**Comment by ai** [comment] 2016-02-15 15:01
Let’ check that `@import` works. Could you put `@import "../../../node_modules/bootstrap/dist/css/bootstrap.css"` in top of CSS to check that it is imported right.

**Comment by ziflex** [comment] 2016-02-15 15:03
```@import``` works.

**Comment by ai** [comment] 2016-02-15 15:05
Could you try without `require('postcss-nested')`?

**Comment by ziflex** [comment] 2016-02-15 15:06
Same result.

**Comment by ai** [comment] 2016-02-15 15:06
OK, let’s wait for @dehuszar

**Comment by dehuszar** [comment] 2016-02-16 16:48
Hey there.  Sorry for the slow reply.  I don't use Gulp that much, so I may have missed something.  I'll try and set up a test env today and reproduce what you're seeing.

**Comment by dehuszar** [comment] 2016-02-16 17:20
Hmm...   I'm seeing what you're seeing.  Shazbot!

Okay.  I have a few fixes and features I've been meaning to push up from my personal machine.  I'll test from there --hopefully this evening.

Thanks, by the way, for giving my plugin a spin.  I'll get you up and running.

**Comment by dehuszar** [comment] 2016-02-20 23:34
@ziflex Hey there,

So, I'm still getting some failing tests (they work on my local, just fighting Travis-CI), but I just pushed up the next release.  Update your test project to 1.0.3 and try running it again.  I am getting the expected output from this updated version.

**Comment by ziflex** [comment] 2016-02-22 02:06
@dehuszar unfortunately still not working :(

**Comment by dehuszar** [comment] 2016-02-22 16:04
Investigating...  I'll try and have an answer for you today.

**Comment by dehuszar** [comment] 2016-02-22 23:12
Okay.  I think I've narrowed the issue down to postcss-import.  I'm able to get the desired output using v7.1.3.  Before I go down that rabbit-hole tracking changes there, can you try this on your end to confirm?

- [clone this gist](https://gist.github.com/dehuszar/0cabbd9bd55372dd5117),
- create a src folder in the gist folder,
- move the style.css into the src folder,
- run `npm install` in the gist's root folder, and then
- run `gulp css`

If the above works your end I'll start looking at what may have changed to postcss-import since v7.x to pinpoint what's causing the breakage.

Thanks!

**Comment by ziflex** [comment] 2016-02-23 15:13
@dehuszar it works!

And I switched to postcss-import v7 in my project and it works as well.

**Comment by ziflex** [comment] 2016-02-23 15:24
@dehuszar but I've found another... not sure whether it's a bug or feature.
But, if I set same reference in multiple files, as result I will get duplicated CSS rules.
The reason why I'm doing this is that I'm trying to make CSS modules and extend my CSS classes with bootstrap classes.

**Comment by dehuszar** [comment] 2016-02-23 17:29
That's great news!  Glad to hear you got it working.

As for the duplicate rules...  Can you post an input / output example of what you're seeing in a new ticket?  It's probably not a bug, but I'd like to see what you're expecting vs seeing.

Without knowing more, I can guess that it is _probably_ because PostCSS-Reference is presently set up (more features coming as time allows) to mimic LESS's class-as-mixin approach.  So when you `@references` a class, you're really dropping a mixin of it rather than `@extend`ing it.  The main reason is, LESS's monolithic-ness allows for other methods to grab in-memory rules that have been `@import (reference)`d, whereas PostCSS has to pass those rules through the AST processor in a way that's difficult for plugins further down the chain do hook into.  So LESS allows for both strategies, this plugin can only do the `@import (reference)`-to-mixin piece at the moment.

My (probably out of date) understanding is that these kinds of cross-plugin hooks is something that the core PostCSS team wants to implement, but as of when I wrote most of the plugin, the platform wasn't quite there yet.  This is something I need to take another look at as I have time.

I have been tossing around a *consolidate* flag idea where, all classes that are referenced would get comma separated above their first instance being used.  Sort of how `@extend` works.  But having `@extend` as a surgical tool feels much better to me than 'all-or-nothing' consolidating.

A couple of ways that could go is to say
```
postcss([...otherPlugs..., reference({
  consolidate: true
})])
```
or
```
postcss([...otherPlugs..., reference({
  consolidate: ['array', 'of', 'selectors', 'to', 'consolidate']
})])
```

But, while the latter approach gives you more precise control, it's a little less composable than doing it in the stylesheet.  It also would start to overload what this one plugin does.

One thing that I haven't tried yet, but can (or if you want to give it a go) is to reference your rules into a %placeholder and then extend that.

So
```css
  %module:references(.btn, .btn-default, .btn-group) {  // bring in Bootstrap dependencies
    // manual rules go here
  }

.my-semantic-class {
  @extend %module;
}
```

or something like that.  [PostCSS-Extend](https://github.com/travco/postcss-extend) is quite capable.  I played with it quite a bit before I decided to create this plugin and I think I remember it doing okay with extending nested objects.  I haven't tried it against the more recent commits of postcss-reference, but you may get some mileage out of that.

If that works, then you could create a template for all your CSS Module templates and then extend them out to semantic classes.

Let me know how your experience goes, or if you have additional questions, or thoughts on the above.  I'm going to close this ticket for now as the original issue has been resolved.

**Closed by dehuszar** 2016-02-23 17:29 UTC

**Comment by ziflex** [comment] 2016-02-26 04:27
@dehuszar thank you for your help!
Now your plugin works as expected. For me it's totally enough :)
